#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# The MIT License (MIT)
#
# Copyright (c) 2015 Alexandre Magno ‒ alexandre.mbm@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
#
#
# INSTRUÇÕES
# ----------
#
# Este comando customizado de git facilita atribuição de autoria.
#
# Instalação:
#
#       export PATH=$PATH:$(pwd)
#
# Uso:
#       git add [ARQUIVOS]
#
#       git coby FULANO "DESCRIÇÃO DO COMMIT"
#
# Onde FULANO é uma chave no dicionário definido abaixo.


author = {
    "alexandre": "Alexandre Magno <alexandre.mbm@gmail.com>",
    "vilmar": "José Vilmar Estácio de Souza <vilmar@informal.com.br>",
    #"lucas": "Lucas Antonio <lucasantoniocwb@gmail.com>",
    "luciano": "Luciano de Souza <luchyanus@gmail.com>",
    #"rafael": "Rafael Renato Gazoni Moreira <linuxacessivel@googlegroups.com>",
    #"rui": "Rui Batista <ruiandrebatista@gmail.com>",
    "tcasal": "Tiago Melo Casal <tcasal@intervox.nce.ufrj.br>",
    "murillo": "Murillo Bolonhini Cita <mbolonhinic@gmail.com>"
}


# As pessoas acima aceitam que suas dicas que tenham sido veiculadas no grupo
# linuxacessivel¹ sejam embutidas no linuxacessivel-book² com a atribuição de
# autoria que pode ser realizada mediante uso deste comando git-coby.
#
# Algumas pessoas estão comentadas (#) por incerteza sobre a vontade delas.
#
# "coby" quer significar "commit by FULANO".


import sys

try:
    a = author[sys.argv[1]]
except IndexError:
    a = None

#print(a)

if not a:
    print('Você precisa especificar um autor.')
    print('Valores possíveis:')
    from tabulate import tabulate
    import operator
    table = sorted(author.items(), key=operator.itemgetter(0))
    print(tabulate(table))
    sys.exit(1)

try:
    m = sys.argv[2]
except IndexError:
    m = None

if not m:
    print('Você precisa descrever o commit.')
    sys.exit(1)


import git

repo = git.Repo('./')
print(repo.git.commit(author=a, m=m))

